In [1]:
import numpy as np

In [2]:
x = np.array([
    [1,6,3] ,
    [7,3,1]
    ])
print(x)
# مصفوفه كام ف كام الشيب بترجعه
print(x.shape)
print(x.ndim)

print(x.dtype)



[[1 6 3]
 [7 3 1]]
(2, 3)
2
int64


## get unique value as set

In [ ]:
np.unique(arr)

In [6]:
x2 =np.array([10,20,30])
print(x2.shape)
print(x2.dtype)

(3,)
int64


In [11]:
y = np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
y =np.eye((3))
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
x = np.arange(0, 10,3)
print(x)

[0 3 6 9]


In [ ]:
x = np.array([
    [10,20,30],
    [1,2,4],
    [1,2,3]
])

print(x[1 ,:])
print(x[0,1])
print(x[:, 0])
print(x [0:2 , 1:3])


[1 2 4]
20
[10  1  1]
[[20 30]
 [ 2  4]]
[[10 20 30  1  2  4  1  2  3]]


## return array of the same size of the origin(x) but bool

In [ ]:
# mask 
print(x>10) 

[[False  True  True]
 [False False False]
 [False False False]]


## return array of element that satisfy mask (condition) (x>10)

In [26]:
print(x[x>10])

[20 30]


## change in the copy here not reflect in the original matrix

In [31]:
x2 =x[0 ,:].copy()
print(x)
print()
print(x2)
x2[0]=100000
print()
print(x2)
print()
print(x)


[[10 20 30]
 [ 1  2  4]
 [ 1  2  3]]

[10 20 30]

[100000     20     30]

[[10 20 30]
 [ 1  2  4]
 [ 1  2  3]]


## so view => when change in the view the changes reflect in the original too

## but copy => not 

In [33]:
x3 =x[0,:].view()

x3[0]=4

print(x3)
print()

print(x)
print()

[ 4 20 30]

[[ 4 20 30]
 [ 1  2  4]
 [ 1  2  3]]



## reshape if matrix nXm so n*m =k , 
مثال احسن 
لو ماتركس 2 *6 
ضربهم 12 
ف لازم اي رقمين تانين يكون ضربهم اتناشر 
زي 3*4 


In [ ]:
x = np.array([
    [2,2,2,2,2],
    [1,2,3,4,5],
    [10,9,8,7,6]
])

print()

print(x.reshape(5,3))

[ 2  2  2  2  2  1  2  3  4  5 10  9  8  7  6]

[[ 2  2  2]
 [ 2  2  1]
 [ 2  3  4]
 [ 5 10  9]
 [ 8  7  6]]


## -1 make it as a one row

In [18]:

print(x.reshape(1,-1))  

[[10 20 30 40]]


## (-1,1) make it as a one column

In [ ]:

print(x.reshape(-1,1))


[[ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 2]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [10]
 [ 9]
 [ 8]
 [ 7]
 [ 6]]


## element-wise operations

In [13]:
y =np.array([
    [1,2,3],
    [3,4,5],
    [6,8,7]
])

z =np.array([
    [5,4,3],
    [2,3,4],
    [1,6,7]
])

print(np.max(z,axis=0)) # get max of each col 
print(np.max(z,axis=1)) # get max of each row  
 
# # adding
# x =y+z
# print(x)

# print()
# x= y*z
# print(x)

[5 6 7]
[5 4 7]


## Matrix Multiplication

In [7]:
x=np.array([
    [1,2,3],
    [1,1,1]
])

y=np.array([
    [2,2,2,2],
    [2,3,4,5],
    [1,2,6,7]
])

print(x.shape)
print(y.shape)

print()

z=np.dot(x,y)
print(z)

(2, 3)
(3, 4)

[[ 9 14 28 33]
 [ 5  7 12 14]]


## sum all element in matrix

In [8]:
print(x.sum())

9


## sum each column when axis=0

In [ ]:
print(x.sum(axis=0 , keepdims=True))

[[2 3 4]]


## sum each row when axis=1

In [11]:
print(x.sum(axis=1 , keepdims=True))

[[6]
 [3]]


## exponent (e power each item in array ) & log10

In [13]:
a =np.exp(x)
print(a)

print()
a= np.log10(x)
print(a)

[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  2.71828183  2.71828183]]

[[0.         0.30103    0.47712125]
 [0.         0.         0.        ]]


## Broadcasting

In [14]:
x =np.array([10,20,30,40])

y =x*2 +1
print(y)

[21 41 61 81]


## give me a random value range of 0 to 9 and make a matrix 2 ,3

In [ ]:

x =np.random.randint(10 ,size=(2,3))
print(x)

[[2 7 1]
 [1 4 0]]


## random.random ramge(0 :1)

In [21]:

x = np.random.random(size=(10,10))
print(x)

[[0.24308013 0.91582205 0.45751568 0.87169742 0.78369624 0.81171713
  0.26394004 0.9779277  0.08429476 0.59392751]
 [0.76980972 0.9374026  0.27407617 0.27158149 0.56950029 0.25706904
  0.92790733 0.07197195 0.58926856 0.42197682]
 [0.43899111 0.02695452 0.23600405 0.60221395 0.07804118 0.61179198
  0.69778672 0.69148816 0.83570858 0.04468759]
 [0.66551688 0.01100264 0.56201622 0.61899301 0.73841305 0.08712251
  0.1253837  0.43500846 0.86459259 0.67422954]
 [0.2753628  0.77592701 0.03355653 0.20462603 0.94912278 0.9918761
  0.22468949 0.57792692 0.64925193 0.79041564]
 [0.72991803 0.57515346 0.48278411 0.80126171 0.45565378 0.93422947
  0.95399345 0.3328421  0.59342607 0.24754096]
 [0.09802868 0.40037905 0.87485291 0.69455972 0.09932156 0.67941778
  0.94247331 0.17807806 0.78716595 0.67577682]
 [0.62503331 0.71402392 0.82706627 0.55654442 0.46258383 0.4492073
  0.87938401 0.83793061 0.0647897  0.39008225]
 [0.5986845  0.70768614 0.25312871 0.62173687 0.64076729 0.98955536
  0.63725954 0

## normal distribution

In [22]:
x=np.random.normal(size=(2,4))
print(x)

[[-0.27587415 -0.34622428 -1.06759558  1.44667319]
 [-0.11367603 -1.35793171  0.23980371  0.23708532]]


## logical operation

In [24]:
x1 =np.array([
    [True ,True ,False],
    [False ,True ,False]
])

x2=np.array([
    [False ,True ,True],
    [True ,False ,True]
])

y= np.logical_and(x1,x2)

print(y )
print()
y=np.logical_or(x1,x2)
print(y )


[[False  True False]
 [False False False]]

[[ True  True  True]
 [ True  True  True]]


In [2]:
x = np.random.rand(100 ,1)
print(x)

[[0.24878704]
 [0.57285874]
 [0.10807331]
 [0.9607552 ]
 [0.2840072 ]
 [0.51113668]
 [0.70571146]
 [0.05529631]
 [0.80298057]
 [0.28270951]
 [0.41883014]
 [0.12910513]
 [0.37137096]
 [0.26057233]
 [0.53944307]
 [0.8986884 ]
 [0.43366619]
 [0.32960185]
 [0.7477012 ]
 [0.67892978]
 [0.14561273]
 [0.8398134 ]
 [0.30231246]
 [0.78342463]
 [0.41974078]
 [0.56842288]
 [0.88147869]
 [0.38663908]
 [0.02115244]
 [0.08943526]
 [0.47115109]
 [0.61035027]
 [0.04297467]
 [0.08479188]
 [0.89184924]
 [0.4532498 ]
 [0.44699347]
 [0.18713007]
 [0.45018668]
 [0.13226546]
 [0.02671894]
 [0.02890244]
 [0.62649733]
 [0.67107442]
 [0.84537968]
 [0.35642461]
 [0.95096208]
 [0.13812927]
 [0.98495151]
 [0.14254066]
 [0.30632007]
 [0.11163233]
 [0.10361335]
 [0.21273215]
 [0.76402249]
 [0.52031626]
 [0.2341547 ]
 [0.86230423]
 [0.31792238]
 [0.18692961]
 [0.48286855]
 [0.55591829]
 [0.69735502]
 [0.50876094]
 [0.03555674]
 [0.99632632]
 [0.72419055]
 [0.39087839]
 [0.54262437]
 [0.31993359]
 [0.03122878]
 [0.31